s:
	gcc -fopenmp -O3 -mavx2 s.c ../../square-matrix-multiplication/matrix/matrix.c
	./a.out left.txt right.txt result.txt
	rm a.out

p:
	gcc -fopenmp -O3 -mavx2 p.c ../../square-matrix-multiplication/matrix/matrix.c
	./a.out left.txt right.txt result.txt
	rm a.out
